### ISSUE TITLE
Did you make the ground truth pair set right?

### ISSUE THREAD

**Issue by qwertyuiopasdfghjklzxcn** [mark-xhchen/IE-CNN#3]
`for cause in true_cause:
                for emo in true_emo:
                    if cause[1] == emo[1]:
                        true_pair.append([cause[0], emo[0]])`
at line 195~198 in ./ours-ecpe/utils/prepare_data.py.
This code segment regards any true emotion clause and true cause clause with the same emotion type, as a ground truth emotion-cause pair. However, the emotion clause and cause clause with the same emotion type doesn't indicate that they form an emotion-cause pair.
For example, while I am debugging, in document 14, this code gives the ground truth emotion-cause pair set {(2,1),(6,1),(2,6),(6,6)}, while the dataset itself gives the ground truth emotion-cause pair set {(2,1), (6,6)}.
In a word, you are evaluating your test set performance on a broader ground truth emotion cause pair set. I would appreciate it if you could give some description.

**Comment by mark-xhchen** [comment]
Thank you for raising this issue. I understand that simply matching the cause and emotion with the same type not necessarily forms a pair. But in the current ECPE dataset, I recalled that for each document, one type of emotion only appears once so what we designed here is still a fair comparison. In other words, the proposed method is not suitable to solve the cases where an emotion type appears multiple times. Feel free to update the codes by yourself and report the new results in your own manuscript. I will also conduct some new experiments later.
